VIEW_WIDTH = 550
MAIN_PADDING = 10
NAV_BTN_SIZE = 48
NAV_WIDTH = MAIN_PADDING * 2 + NAV_BTN_SIZE
SHADOW_SIZE = 8
PAGE_WIDTH = NAV_WIDTH + VIEW_WIDTH + SHADOW_SIZE * 2
PAGE_HEIGHT = 800 + SHADOW_SIZE * 2
